OreburghHouseOne_MapScripts::
	.byte 0


OreburghCityNorthwestHouse1F_Text_RoarkLetsUsTrainOurPokemonInTheMine::
# 4 "data/maps/OreburghHouseOne/scripts.pory"
	lock
# 5 "data/maps/OreburghHouseOne/scripts.pory"
	msgbox OreburghCityNorthwestHouse1F_Text_RoarkLetsUsTrainOurPokemonInTheMine_Text_0, MSGBOX_NPC
# 7 "data/maps/OreburghHouseOne/scripts.pory"
	release
	return


OreburghCityNorthwestHouse1F_Text_AGymLeaderIsntLikeJustAnyTrainerYouMeet::
# 11 "data/maps/OreburghHouseOne/scripts.pory"
	lock
# 12 "data/maps/OreburghHouseOne/scripts.pory"
	msgbox OreburghCityNorthwestHouse1F_Text_AGymLeaderIsntLikeJustAnyTrainerYouMeet_Text_0, MSGBOX_NPC
# 18 "data/maps/OreburghHouseOne/scripts.pory"
	release
	return


OreburghCityNorthwestHouse1F_Text_ThereAreEightGymLeadersInTheSinnohRegion::
# 22 "data/maps/OreburghHouseOne/scripts.pory"
	lock
# 23 "data/maps/OreburghHouseOne/scripts.pory"
	msgbox OreburghCityNorthwestHouse1F_Text_ThereAreEightGymLeadersInTheSinnohRegion_Text_0, MSGBOX_NPC
# 29 "data/maps/OreburghHouseOne/scripts.pory"
	release
	return


OreburghCityNorthwestHouse1F_Text_RoarkLetsUsTrainOurPokemonInTheMine_Text_0:
# 5 "data/maps/OreburghHouseOne/scripts.pory"
	.string "Roark lets us train our Pokémon in\n"
	.string "the mine.$"

OreburghCityNorthwestHouse1F_Text_AGymLeaderIsntLikeJustAnyTrainerYouMeet_Text_0:
# 12 "data/maps/OreburghHouseOne/scripts.pory"
	.string "A Gym Leader isn’t like just any Trainer\n"
	.string "you meet.\p"
	.string "Obviously, they’re a lot tougher.\n"
	.string "A lot.\p"
	.string "I’d take as many Pokémon as possible\n"
	.string "if I were you.$"

OreburghCityNorthwestHouse1F_Text_ThereAreEightGymLeadersInTheSinnohRegion_Text_0:
# 23 "data/maps/OreburghHouseOne/scripts.pory"
	.string "There are eight Gym Leaders in the\n"
	.string "Sinnoh region.\p"
	.string "The objective for Trainers is to get\n"
	.string "Gym Badges from them all.\p"
	.string "That means you have to defeat all of\n"
	.string "them in battles at their Gyms!$"
