Oreburgh_museum_MapScripts::
	.byte 0


MiningMuseum_Text_WelcomeToMuseum::
# 4 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 5 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_WelcomeToMuseum_Text_0, MSGBOX_NPC
# 7 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_FossilResearcherGreeting::
# 11 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 12 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_FossilResearcherGreeting_Text_0, MSGBOX_NPC
# 16 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_CoalExhibit1::
# 20 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 21 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_CoalExhibit1_Text_0, MSGBOX_NPC
# 25 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_CoalExhibit2::
# 29 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 30 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_CoalExhibit2_Text_0, MSGBOX_NPC
# 32 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_MineExtendsUnderSea::
# 36 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 37 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_MineExtendsUnderSea_Text_0, MSGBOX_NPC
# 40 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_MineHistory::
# 44 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 45 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_MineHistory_Text_0, MSGBOX_NPC
# 49 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_UndergroundManInfo::
# 53 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 54 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_UndergroundManInfo_Text_0, MSGBOX_NPC
# 60 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_HowCoalIsMade1::
# 64 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 65 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_HowCoalIsMade1_Text_0, MSGBOX_SIGN
# 70 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_HowCoalIsMade2::
# 74 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 75 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_HowCoalIsMade2_Text_0, MSGBOX_SIGN
# 80 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_HowCoalIsMade3::
# 84 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 85 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_HowCoalIsMade3_Text_0, MSGBOX_SIGN
# 90 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_SamplesDifferentRegions::
# 94 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 95 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_SamplesDifferentRegions_Text_0, MSGBOX_SIGN
# 97 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_CategorizedCoalSamples::
# 101 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 102 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_CategorizedCoalSamples_Text_0, MSGBOX_SIGN
# 104 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_MiningLamps::
# 108 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 109 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_MiningLamps_Text_0, MSGBOX_SIGN
# 113 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_MiningTools::
# 117 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 118 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_MiningTools_Text_0, MSGBOX_SIGN
# 122 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_MineWorkerItems::
# 126 "data/maps/Oreburgh_museum/scripts.pory"
	lock
# 127 "data/maps/Oreburgh_museum/scripts.pory"
	msgbox MiningMuseum_Text_MineWorkerItems_Text_0, MSGBOX_SIGN
# 129 "data/maps/Oreburgh_museum/scripts.pory"
	release
	return


MiningMuseum_Text_WelcomeToMuseum_Text_0:
# 5 "data/maps/Oreburgh_museum/scripts.pory"
	.string "Hello! Welcome to the Oreburgh\n"
	.string "Mining Museum!$"

MiningMuseum_Text_FossilResearcherGreeting_Text_0:
# 12 "data/maps/Oreburgh_museum/scripts.pory"
	.string "Hello, hello!\n"
	.string "How are you?\p"
	.string "I study Pokémon Fossils!\n"
	.string "Me! Right here and now!\p$"

MiningMuseum_Text_CoalExhibit1_Text_0:
# 21 "data/maps/Oreburgh_museum/scripts.pory"
	.string "Whoa! So this is coal?\n"
	.string "I never expected something this big!\p"
	.string "And that color!\n"
	.string "It really is as black as they say!$"

MiningMuseum_Text_CoalExhibit2_Text_0:
# 30 "data/maps/Oreburgh_museum/scripts.pory"
	.string "Wow! The Pokémon that carried this\n"
	.string "must be terribly strong!$"

MiningMuseum_Text_MineExtendsUnderSea_Text_0:
# 37 "data/maps/Oreburgh_museum/scripts.pory"
	.string "Well, how about that!\p"
	.string "The Oreburgh Mine extends under\n"
	.string "the seafloor!$"

MiningMuseum_Text_MineHistory_Text_0:
# 45 "data/maps/Oreburgh_museum/scripts.pory"
	.string "The history of Oreburgh Mine...\p"
	.string "You could call it a history of effort\n"
	.string "and friendship between people\l"
	.string "and Pokémon.$"

MiningMuseum_Text_UndergroundManInfo_Text_0:
# 54 "data/maps/Oreburgh_museum/scripts.pory"
	.string "It’s a little far from here, but there\n"
	.string "is a city called Eterna City.\p"
	.string "I’ve heard a curious person named the\n"
	.string "Underground Man lives there.\p"
	.string "With a name like that, he must be an\n"
	.string "authority on the Underground.$"

MiningMuseum_Text_HowCoalIsMade1_Text_0:
# 65 "data/maps/Oreburgh_museum/scripts.pory"
	.string "How Coal Is Made   1:\p"
	.string "In a time long before history,\n"
	.string "vegetative matter was swept along\p"
	.string "by rain and rivers. It came to be\n"
	.string "buried under the ground.$"

MiningMuseum_Text_HowCoalIsMade2_Text_0:
# 75 "data/maps/Oreburgh_museum/scripts.pory"
	.string "How Coal Is Made   2:\p"
	.string "The buried plant matter was\n"
	.string "forced ever deeper under the ground\p"
	.string "due to tremors and fissures caused\n"
	.string "by the shifting landmasses.$"

MiningMuseum_Text_HowCoalIsMade3_Text_0:
# 85 "data/maps/Oreburgh_museum/scripts.pory"
	.string "How Coal Is Made   3:\p"
	.string "Deep under the ground, the\n"
	.string "plant matter was subjected to heavy\p"
	.string "pressure and the heat of magma.\n"
	.string "It gradually turned into coal.$"

MiningMuseum_Text_SamplesDifferentRegions_Text_0:
# 95 "data/maps/Oreburgh_museum/scripts.pory"
	.string "Samples of coal from different regions\n"
	.string "are displayed.$"

MiningMuseum_Text_CategorizedCoalSamples_Text_0:
# 102 "data/maps/Oreburgh_museum/scripts.pory"
	.string "The box contains categorized samples\n"
	.string "of coal.$"

MiningMuseum_Text_MiningLamps_Text_0:
# 109 "data/maps/Oreburgh_museum/scripts.pory"
	.string "Different kinds of lamps are\n"
	.string "displayed.\p"
	.string "They appear to have been worn\n"
	.string "on someone’s head while underground.$"

MiningMuseum_Text_MiningTools_Text_0:
# 118 "data/maps/Oreburgh_museum/scripts.pory"
	.string "Badly scarred wooden tools are\n"
	.string "displayed.\p"
	.string "They apparently dug out coal using\n"
	.string "these tools in the olden days.$"

MiningMuseum_Text_MineWorkerItems_Text_0:
# 127 "data/maps/Oreburgh_museum/scripts.pory"
	.string "The everyday items and tools of\n"
	.string "past mine workers are displayed.$"
