Oreburgh_Small_House_Three_MapScripts::
	.byte 0


OreburghCitySouthHouse_Text_YoureTakingATourOfOurCoalMine::
# 4 "data/maps/Oreburgh_Small_House_Three/scripts.pory"
	lock
# 5 "data/maps/Oreburgh_Small_House_Three/scripts.pory"
	msgbox OreburghCitySouthHouse_Text_YoureTakingATourOfOurCoalMine_Text_0, MSGBOX_NPC
# 10 "data/maps/Oreburgh_Small_House_Three/scripts.pory"
	release
	return


OreburghCitySouthHouse_Text_YoureTakingATourOfOurCoalMine_Text_0:
# 5 "data/maps/Oreburgh_Small_House_Three/scripts.pory"
	.string "You’re taking a tour of our coal mine?\p"
	.string "Wonderful!\n"
	.string "That’s excellent of you.\p"
	.string "It’s always good to learn about new\n"
	.string "things and broaden your horizons!$"
