Route207_MapScripts::
	.byte 0


Route207_Text_ThatSlopesTooSlippery::
# 4 "data/maps/Route207/scripts.pory"
	lock
# 5 "data/maps/Route207/scripts.pory"
	msgbox Route207_Text_ThatSlopesTooSlippery_Text_0, MSGBOX_NPC
# 9 "data/maps/Route207/scripts.pory"
	release
	return


Route207_Text_ThatSlopesTooSlippery_Text_0:
# 5 "data/maps/Route207/scripts.pory"
	.string "That slope’s too slippery.\n"
	.string "You’ll need a Bike to get up.\p"
	.string "You don’t have a Bicycle?\n"
	.string "There’s a Cycle Shop in Eterna City.$"
