#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_BARRY,
    SP_NAME_DAWN,
    SP_NAME_LUCAS,
    SP_NAME_ROWAN,
    SP_NAME_CYRUS,
    SP_NAME_IDK,
    SP_NAME_LOOKER,
    SP_NAME_ROARK,
    SP_NAME_GARDENIA,
    SP_NAME_MAYLENE,
    SP_NAME_WAKE,
    SP_NAME_FANTINA,
    SP_NAME_BYRON,
    SP_NAME_CANDICE,
    SP_NAME_VOLKNER,
    SP_NAME_MARS,
    SP_NAME_JUPITER,
    SP_NAME_SATURN,
    SP_NAME_CHARON,
    SP_NAME_CEDRUS,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
