#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(WORK_UP) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(DRAINING_KISS) \
    F(TOXIC) \
    F(SNOWSCAPE) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(BULLDOZE) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TRAILBLAZE) \
    F(FACADE) \
    F(LIQUIDATION) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(PLAY_ROUGH) \
    F(NASTY_PLOT) \
    F(OVERHEAT) \
    F(ROOST) \
    F(FOCUS_BLAST) \
    F(ENERGY_BALL) \
    F(FALSE_SWIPE) \
    F(BRINE) \
    F(POWER_GEM) \
    F(CHARGE_BEAM) \
    F(FROST_BREATH) \
    F(DRAGON_PULSE) \
    F(DRAIN_PUNCH) \
    F(WILL_O_WISP) \
    F(SILVER_WIND) \
    F(AURORA_VEIL) \
    F(EARTH_POWER) \
    F(SHADOW_CLAW) \
    F(PAYBACK) \
    F(MAGICAL_LEAF) \
    F(GIGA_IMPACT) \
    F(ROCK_POLISH) \
    F(SMART_STRIKE) \
    F(STONE_EDGE) \
    F(AVALANCHE) \
    F(THUNDER_WAVE) \
    F(GYRO_BALL) \
    F(SWORDS_DANCE) \
    F(STEALTH_ROCK) \
    F(LEECH_LIFE) \
    F(CHARM) \
    F(DARK_PULSE) \
    F(ROCK_SLIDE) \
    F(X_SCISSOR) \
    F(STRUGGLE_BUG) \
    F(FLAME_CHARGE) \
    F(POISON_JAB) \
    F(TRIPLE_AXEL) \
    F(GRASS_KNOT) \
    F(ACID_SPRAY) \
    F(PLUCK) \
    F(U_TURN) \
    F(SKITTER_SMACK) \
    F(FLASH_CANNON) \
    F(TRICK_ROOM) \
    F(FIRE_FANG) \
    F(THUNDER_FANG) \
    F(ICE_FANG) \
    F(POISON_FANG) \
    F(PSYCHIC_FANGS) \
    F(WILD_CHARGE) \
    F(MOONBLAST) \
    F(BREAKING_SWIPE) 

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
