gText_Birch_Welcome::
	.string "Hello there!\n"
	.string "It’s so very nice to meet you!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Rowan.\p"
	.string "However, everyone just calls me\n"
	.string "the Pokémon Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "We humans live alongside Pokémon\n"
	.string "as friends.\p"
	.string "At times we play together,\n"
	.string "and at other times we\l"
	.string "work together.\p"
	.string "Some people use their Pokémon\n"
	.string "to battle and develop.\l"
	.string "closer bonds with them.\p"
	.string "What do I do?\p"
	.string "I conduct research so that we may\n"
	.string "learn more about Pokémon.\p"
	.string "Now, why don’t you tell me\n"
	.string "a little bit about yourself?\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now, why don’t you tell me\n"
	.string "a little bit about yourself?\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "Your name is {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "OK...\n"
	.string "So you're {PLAYER}{KUN}?\p"
	.string "A fine name that is!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, {PLAYER}{KUN}, the time\n"
	.string "has come.\p"
    .string "Your very own tale of grand\n"
    .string "adventure is about to unfold.\p"
    .string "On your journey, you will meet\n"
    .string "countless Pokémon and people.\p"
    .string "I’m sure that along the way you will\n"
    .string "discover many things, perhaps even\l"
    .string "something about yourself.\p"
    .string "Now, go on, leap into the world of\n"
    .string "Pokémon!\p"
	.string "$"
