JubilifeCompanyF3_MapScripts::
	.byte 0


PoketchCo3F_Text_MyHusbandsThePresident::
# 4 "data/maps/JubilifeCompanyF3/scripts.pory"
	lock
# 5 "data/maps/JubilifeCompanyF3/scripts.pory"
	msgbox PoketchCo3F_Text_MyHusbandsThePresident_Text_0, MSGBOX_NPC
# 10 "data/maps/JubilifeCompanyF3/scripts.pory"
	release
	return


PoketchCo3F_Text_TheresAGirlsModelAndABoysModel::
# 14 "data/maps/JubilifeCompanyF3/scripts.pory"
	lock
# 15 "data/maps/JubilifeCompanyF3/scripts.pory"
	msgbox PoketchCo3F_Text_TheresAGirlsModelAndABoysModel_Text_0, MSGBOX_NPC
# 18 "data/maps/JubilifeCompanyF3/scripts.pory"
	release
	return


PoketchCo3F_Text_PeopleEverywhereMakePoketchApps::
# 22 "data/maps/JubilifeCompanyF3/scripts.pory"
	lock
# 23 "data/maps/JubilifeCompanyF3/scripts.pory"
	msgbox PoketchCo3F_Text_PeopleEverywhereMakePoketchApps_Text_0, MSGBOX_NPC
# 28 "data/maps/JubilifeCompanyF3/scripts.pory"
	release
	return


PoketchCo3F_Text_ThereAreDescriptionsOfPoketchApps1::
# 32 "data/maps/JubilifeCompanyF3/scripts.pory"
	lock
# 33 "data/maps/JubilifeCompanyF3/scripts.pory"
	msgbox PoketchCo3F_Text_ThereAreDescriptionsOfPoketchApps1_Text_0, MSGBOX_SIGN
# 35 "data/maps/JubilifeCompanyF3/scripts.pory"
	release
	return


PoketchCo3F_Text_MyHusbandsThePresident_Text_0:
# 5 "data/maps/JubilifeCompanyF3/scripts.pory"
	.string "My husband’s the president.\p"
	.string "We started out in a small workshop\n"
	.string "where he made what he liked.\p"
	.string "Now we’re making something that makes\n"
	.string "the world happy. Imagine that!$"

PoketchCo3F_Text_TheresAGirlsModelAndABoysModel_Text_0:
# 15 "data/maps/JubilifeCompanyF3/scripts.pory"
	.string "Do you have a Pokétch?\p"
	.string "There’s a girl’s model and a boy’s\n"
	.string "model, each in different colors.$"

PoketchCo3F_Text_PeopleEverywhereMakePoketchApps_Text_0:
# 23 "data/maps/JubilifeCompanyF3/scripts.pory"
	.string "People everywhere make Pokétch apps.\p"
	.string "You’ll be able to get new apps from\n"
	.string "surprising sources.\p"
	.string "The PCs here have guides on the\n"
	.string "various Pokétch apps.$"

PoketchCo3F_Text_ThereAreDescriptionsOfPoketchApps1_Text_0:
# 33 "data/maps/JubilifeCompanyF3/scripts.pory"
	.string "There are descriptions of Pokétch\n"
	.string "apps.$"
