OreburghHouseTwo_F2_MapScripts::
	.byte 0


OreburghCityNorthHouse2F_Text_AllPokemonHaveASpecialPowerCalledAnAbility::
# 4 "data/maps/OreburghHouseTwo_F2/scripts.pory"
	lock
# 5 "data/maps/OreburghHouseTwo_F2/scripts.pory"
	msgbox OreburghCityNorthHouse2F_Text_AllPokemonHaveASpecialPowerCalledAnAbility_Text_0, MSGBOX_NPC
# 7 "data/maps/OreburghHouseTwo_F2/scripts.pory"
	release
	return


OreburghCityNorthHouse2F_Text_MyFavoritePokemonAbilityIsMyPachirisusPickup::
# 11 "data/maps/OreburghHouseTwo_F2/scripts.pory"
	lock
# 12 "data/maps/OreburghHouseTwo_F2/scripts.pory"
	msgbox OreburghCityNorthHouse2F_Text_MyFavoritePokemonAbilityIsMyPachirisusPickup_Text_0, MSGBOX_NPC
# 16 "data/maps/OreburghHouseTwo_F2/scripts.pory"
	release
	return


OreburghCityNorthHouse2F_Text_HowAboutShowingMeAPokemonCalledGeodude::
# 20 "data/maps/OreburghHouseTwo_F2/scripts.pory"
	lock
# 21 "data/maps/OreburghHouseTwo_F2/scripts.pory"
	msgbox OreburghCityNorthHouse2F_Text_HowAboutShowingMeAPokemonCalledGeodude_Text_0, MSGBOX_NPC
# 25 "data/maps/OreburghHouseTwo_F2/scripts.pory"
	release
	return


OreburghCityNorthHouse2F_Text_AllPokemonHaveASpecialPowerCalledAnAbility_Text_0:
# 5 "data/maps/OreburghHouseTwo_F2/scripts.pory"
	.string "All Pokémon have a special power\n"
	.string "called an ability.$"

OreburghCityNorthHouse2F_Text_MyFavoritePokemonAbilityIsMyPachirisusPickup_Text_0:
# 12 "data/maps/OreburghHouseTwo_F2/scripts.pory"
	.string "My favorite Pokémon ability is my\n"
	.string "Pachirisu’s Pickup.\p"
	.string "My darling picks up a lot of dropped\n"
	.string "items without me noticing!$"

OreburghCityNorthHouse2F_Text_HowAboutShowingMeAPokemonCalledGeodude_Text_0:
# 21 "data/maps/OreburghHouseTwo_F2/scripts.pory"
	.string "The view is good from the second floor,\n"
	.string "but it’s a pain going outside.\p"
	.string "If you don’t mind, how about showing me\n"
	.string "a Pokémon called Geodude?$"
