Sandgem_House_One_2_MapScripts::
	.byte 0


SandgemTownHouse_Text_PokemonGrowStrongerFromBattlingOtherPokemon::
# 4 "data/maps/Sandgem_House_One_2/scripts.pory"
	lock
# 5 "data/maps/Sandgem_House_One_2/scripts.pory"
	msgbox SandgemTownHouse_Text_PokemonGrowStrongerFromBattlingOtherPokemon_Text_0, MSGBOX_NPC
# 11 "data/maps/Sandgem_House_One_2/scripts.pory"
	release
	return


SandgemTownHouse_Text_AGoodTrainerTakesCareToNotLetTheirPokemonFaint::
# 16 "data/maps/Sandgem_House_One_2/scripts.pory"
	lock
# 17 "data/maps/Sandgem_House_One_2/scripts.pory"
	msgbox SandgemTownHouse_Text_AGoodTrainerTakesCareToNotLetTheirPokemonFaint_Text_0, MSGBOX_NPC
# 20 "data/maps/Sandgem_House_One_2/scripts.pory"
	release
	return


SandgemTownHouse_Text_PokemonGrowStrongerFromBattlingOtherPokemon_Text_0:
# 5 "data/maps/Sandgem_House_One_2/scripts.pory"
	.string "Pokémon grow steadily stronger from\n"
	.string "battling against other Pokémon.\p"
	.string "At first, you should take it easy,\n"
	.string "though.\p"
	.string "Heal your Pokémon regularly at Pokémon\n"
	.string "Centers while you’re leveling them up.$"

SandgemTownHouse_Text_AGoodTrainerTakesCareToNotLetTheirPokemonFaint_Text_0:
# 17 "data/maps/Sandgem_House_One_2/scripts.pory"
	.string "A good Trainer is one that takes care\n"
	.string "not to let their Pokémon faint from\l"
	.string "losing HP.$"
