Oreburgh_Small_House_Two_MapScripts::
	.byte 0


OreburghCityMiddleHouse_Text_RoarkIsAUserOfRockTypePokemon::
# 4 "data/maps/Oreburgh_Small_House_Two/scripts.pory"
	lock
# 5 "data/maps/Oreburgh_Small_House_Two/scripts.pory"
	msgbox OreburghCityMiddleHouse_Text_RoarkIsAUserOfRockTypePokemon_Text_0, MSGBOX_NPC
# 8 "data/maps/Oreburgh_Small_House_Two/scripts.pory"
	release
	return


OreburghCityMiddleHouse_Text_RoarkIsOurTownsGymLeader::
# 12 "data/maps/Oreburgh_Small_House_Two/scripts.pory"
	lock
# 13 "data/maps/Oreburgh_Small_House_Two/scripts.pory"
	msgbox OreburghCityMiddleHouse_Text_RoarkIsOurTownsGymLeader_Text_0, MSGBOX_NPC
# 16 "data/maps/Oreburgh_Small_House_Two/scripts.pory"
	release
	return


OreburghCityMiddleHouse_Text_RoarkIsAUserOfRockTypePokemon_Text_0:
# 5 "data/maps/Oreburgh_Small_House_Two/scripts.pory"
	.string "Roark is a user of Rock-type Pokémon.\p"
	.string "Don’t you think Rock-type Pokémon are\n"
	.string "nice? I like how lumpy they are!$"

OreburghCityMiddleHouse_Text_RoarkIsOurTownsGymLeader_Text_0:
# 13 "data/maps/Oreburgh_Small_House_Two/scripts.pory"
	.string "Roark is our town’s Gym Leader.\p"
	.string "He may be young, but he keeps the\n"
	.string "mine running safely and efficiently.$"
