Oreburgh_Mine_MapScripts::
	.byte 0


OreburghMineB1F_Text_EveryoneThatWorksInTheCoalMineKeepsTheirOwnPokemonWithThem::
# 4 "data/maps/Oreburgh_Mine/scripts.pory"
	lock
# 5 "data/maps/Oreburgh_Mine/scripts.pory"
	msgbox OreburghMineB1F_Text_EveryoneThatWorksInTheCoalMineKeepsTheirOwnPokemonWithThem_Text_0, MSGBOX_NPC
# 9 "data/maps/Oreburgh_Mine/scripts.pory"
	release
	return


OreburghMineB1F_Text_IFoundWhatIThoughtWereSomeRocksThenTheyStartedMoving::
# 13 "data/maps/Oreburgh_Mine/scripts.pory"
	lock
# 14 "data/maps/Oreburgh_Mine/scripts.pory"
	msgbox OreburghMineB1F_Text_IFoundWhatIThoughtWereSomeRocksThenTheyStartedMoving_Text_0, MSGBOX_NPC
# 18 "data/maps/Oreburgh_Mine/scripts.pory"
	release
	return


OreburghMineB1F_Text_EveryoneThatWorksInTheCoalMineKeepsTheirOwnPokemonWithThem_Text_0:
# 5 "data/maps/Oreburgh_Mine/scripts.pory"
	.string "Everyone that works in the coal mine\n"
	.string "keeps their own Pokémon with them.\p"
	.string "You may be challenged to battles!\n"
	.string "Hahaha!$"

OreburghMineB1F_Text_IFoundWhatIThoughtWereSomeRocksThenTheyStartedMoving_Text_0:
# 14 "data/maps/Oreburgh_Mine/scripts.pory"
	.string "I found what I thought were some\n"
	.string "rocks, then they started moving!\p"
	.string "They were Pokémon that looked just\n"
	.string "like rocks!$"
