JubilifeHouseThree_F2_MapScripts::
	.byte 0


JubilifeCityCondominiums2F_Text_ILikeHowPokemonCanUseAttacks::
# 4 "data/maps/JubilifeHouseThree_F2/scripts.pory"
	lock
# 5 "data/maps/JubilifeHouseThree_F2/scripts.pory"
	msgbox JubilifeCityCondominiums2F_Text_ILikeHowPokemonCanUseAttacks_Text_0, MSGBOX_NPC
# 11 "data/maps/JubilifeHouseThree_F2/scripts.pory"
	release
	return


JubilifeCityCondominiums2F_Text_DidYouBuySomeHealBallsAtThePokeMart::
# 15 "data/maps/JubilifeHouseThree_F2/scripts.pory"
	lock
# 16 "data/maps/JubilifeHouseThree_F2/scripts.pory"
	msgbox JubilifeCityCondominiums2F_Text_DidYouBuySomeHealBallsAtThePokeMart_Text_0, MSGBOX_NPC
# 24 "data/maps/JubilifeHouseThree_F2/scripts.pory"
	release
	return


JubilifeCityCondominiums2F_Text_ILikeHowPokemonCanUseAttacks_Text_0:
# 5 "data/maps/JubilifeHouseThree_F2/scripts.pory"
	.string "I like how Pokémon can use attacks.\n"
	.string "That makes things fun and different.\p"
	.string "Sometimes, when they get stronger,\n"
	.string "Pokémon learn new moves.\p"
	.string "That keeps things fresh and fun when\n"
	.string "using moves.$"

JubilifeCityCondominiums2F_Text_DidYouBuySomeHealBallsAtThePokeMart_Text_0:
# 16 "data/maps/JubilifeHouseThree_F2/scripts.pory"
	.string "Did you buy some Heal Balls at the\n"
	.string "Poké Mart?\p"
	.string "A Heal Ball completely heals the\n"
	.string "Pokémon it captures on the spot.\p"
	.string "That means you can catch a Pokémon\n"
	.string "and have it battle-ready right away.\p"
	.string "Of course, if your team has six\n"
	.string "Pokémon in it, it won’t do any good.$"
