JubilifeHouseOne_F2_MapScripts::
	.byte 0


JubilifeCitySouthHouse2F_SomeKindsOfPokemonEvolveWhenTheyGetStrongerFromBattling::
# 4 "data/maps/JubilifeHouseOne_F2/scripts.pory"
	lock
# 5 "data/maps/JubilifeHouseOne_F2/scripts.pory"
	msgbox JubilifeCitySouthHouse2F_SomeKindsOfPokemonEvolveWhenTheyGetStrongerFromBattling_Text_0, MSGBOX_NPC
# 10 "data/maps/JubilifeHouseOne_F2/scripts.pory"
	release
	return


JubilifeCitySouthHouse2F_EvolutionMakesPokemonJustThatMuchMoreFascinating::
# 14 "data/maps/JubilifeHouseOne_F2/scripts.pory"
	lock
# 15 "data/maps/JubilifeHouseOne_F2/scripts.pory"
	msgbox JubilifeCitySouthHouse2F_EvolutionMakesPokemonJustThatMuchMoreFascinating_Text_0, MSGBOX_NPC
# 19 "data/maps/JubilifeHouseOne_F2/scripts.pory"
	release
	return


JubilifeCitySouthHouse2F_DidntProfRowanConductResearchWithProfOak::
# 23 "data/maps/JubilifeHouseOne_F2/scripts.pory"
	lock
# 24 "data/maps/JubilifeHouseOne_F2/scripts.pory"
	msgbox JubilifeCitySouthHouse2F_DidntProfRowanConductResearchWithProfOak_Text_0, MSGBOX_NPC
# 26 "data/maps/JubilifeHouseOne_F2/scripts.pory"
	release
	return


JubilifeCitySouthHouse2F_SomeKindsOfPokemonEvolveWhenTheyGetStrongerFromBattling_Text_0:
# 5 "data/maps/JubilifeHouseOne_F2/scripts.pory"
	.string "Did you know?\p"
	.string "Some kinds of Pokémon evolve when\n"
	.string "they get stronger from battling!\p"
	.string "When they evolve, they can take on\n"
	.string "completely different forms!$"

JubilifeCitySouthHouse2F_EvolutionMakesPokemonJustThatMuchMoreFascinating_Text_0:
# 15 "data/maps/JubilifeHouseOne_F2/scripts.pory"
	.string "Evolution makes Pokémon just that\n"
	.string "much more fascinating.\p"
	.string "The mysteries of evolution... Can that\n"
	.string "dandy Prof. Rowan unravel them?$"

JubilifeCitySouthHouse2F_DidntProfRowanConductResearchWithProfOak_Text_0:
# 24 "data/maps/JubilifeHouseOne_F2/scripts.pory"
	.string "Didn’t Prof. Rowan conduct research\n"
	.string "with Prof. Oak of the Kanto region?$"
