OreburghHouseThree_MapScripts::
	.byte 0


OreburghCityEastHouse1F_Text_WhyNotTryTrainingInTheOreburghMine::
# 4 "data/maps/OreburghHouseThree/scripts.pory"
	lock
# 5 "data/maps/OreburghHouseThree/scripts.pory"
	msgbox OreburghCityEastHouse1F_Text_WhyNotTryTrainingInTheOreburghMine_Text_0, MSGBOX_NPC
# 9 "data/maps/OreburghHouseThree/scripts.pory"
	release
	return


OreburghCityEastHouse1F_Text_IAlwaysHaveARottenTimeTryingToDecideWhichMovesMyPokemonShouldLearn::
# 13 "data/maps/OreburghHouseThree/scripts.pory"
	lock
# 14 "data/maps/OreburghHouseThree/scripts.pory"
	msgbox OreburghCityEastHouse1F_Text_IAlwaysHaveARottenTimeTryingToDecideWhichMovesMyPokemonShouldLearn_Text_0, MSGBOX_NPC
# 17 "data/maps/OreburghHouseThree/scripts.pory"
	release
	return


OreburghCityEastHouse1F_Text_YouRemindMeSoMuchOfTheTimeIGotMyFirstPokemon::
# 21 "data/maps/OreburghHouseThree/scripts.pory"
	lock
# 22 "data/maps/OreburghHouseThree/scripts.pory"
	msgbox OreburghCityEastHouse1F_Text_YouRemindMeSoMuchOfTheTimeIGotMyFirstPokemon_Text_0, MSGBOX_NPC
# 24 "data/maps/OreburghHouseThree/scripts.pory"
	release
	return


OreburghCityEastHouse1F_Text_WhyNotTryTrainingInTheOreburghMine_Text_0:
# 5 "data/maps/OreburghHouseThree/scripts.pory"
	.string "Hiya! Your Pokémon could use some\n"
	.string "toughening up.\p"
	.string "Why not try training in\n"
	.string "the Oreburgh Mine?$"

OreburghCityEastHouse1F_Text_IAlwaysHaveARottenTimeTryingToDecideWhichMovesMyPokemonShouldLearn_Text_0:
# 14 "data/maps/OreburghHouseThree/scripts.pory"
	.string "I always have a rotten time trying\n"
	.string "to decide which moves my Pokémon\l"
	.string "should learn.$"

OreburghCityEastHouse1F_Text_YouRemindMeSoMuchOfTheTimeIGotMyFirstPokemon_Text_0:
# 22 "data/maps/OreburghHouseThree/scripts.pory"
	.string "You remind me so much of the time\n"
	.string "I got my first Pokémon.$"
