ROUTE204_MapScripts::
	.byte 0


Route204South_Text_Rt204JubilifeCity::
# 4 "data/maps/ROUTE204/scripts.pory"
	lock
# 5 "data/maps/ROUTE204/scripts.pory"
	msgbox Route204South_Text_Rt204JubilifeCity_Text_0, MSGBOX_SIGN
	return


Route204South_Text_RavagedPath::
# 10 "data/maps/ROUTE204/scripts.pory"
	lock
# 11 "data/maps/ROUTE204/scripts.pory"
	msgbox Route204South_Text_Rt204JubilifeCity_Text_0, MSGBOX_SIGN
	return


Route204South_Text_ThereAreBouldersBlockingTheWayInsideTheCavern::
# 16 "data/maps/ROUTE204/scripts.pory"
	lock
# 17 "data/maps/ROUTE204/scripts.pory"
	msgbox Route204South_Text_ThereAreBouldersBlockingTheWayInsideTheCavern_Text_0, MSGBOX_NPC
	return


Route204South_Text_Rt204JubilifeCity_Text_0:
# 5 "data/maps/ROUTE204/scripts.pory"
	.string "Rt. 204\n"
	.string "Jubilife City$"

Route204South_Text_ThereAreBouldersBlockingTheWayInsideTheCavern_Text_0:
# 17 "data/maps/ROUTE204/scripts.pory"
	.string "There are boulders blocking the way\n"
	.string "inside the cavern...\p"
	.string "I think a Pokémon’s hidden move will be\n"
	.string "able to smash those boulders, though.$"
