JubilifeCompanyF1_MapScripts::
	.byte 0


PoketchCo1F_Text_WelcomeToThePoketchCompany::
# 4 "data/maps/JubilifeCompanyF1/scripts.pory"
	lock
# 5 "data/maps/JubilifeCompanyF1/scripts.pory"
	msgbox PoketchCo1F_Text_WelcomeToThePoketchCompany_Text_0, MSGBOX_NPC
# 8 "data/maps/JubilifeCompanyF1/scripts.pory"
	release
	return


PoketchCo1F_Text_OhYouCanBeSureIWillKeepDevelopingPoketchApps::
# 12 "data/maps/JubilifeCompanyF1/scripts.pory"
	lock
# 13 "data/maps/JubilifeCompanyF1/scripts.pory"
	msgbox PoketchCo1F_Text_OhYouCanBeSureIWillKeepDevelopingPoketchApps_Text_0, MSGBOX_NPC
# 17 "data/maps/JubilifeCompanyF1/scripts.pory"
	release
	return


PoketchCo1F_Text_HeyDoYouWatchTV::
# 21 "data/maps/JubilifeCompanyF1/scripts.pory"
	lock
# 22 "data/maps/JubilifeCompanyF1/scripts.pory"
	msgbox PoketchCo1F_Text_HeyDoYouWatchTV_Text_0, MSGBOX_NPC
# 26 "data/maps/JubilifeCompanyF1/scripts.pory"
	release
	return


PoketchCo1F_Text_WithTV::
# 30 "data/maps/JubilifeCompanyF1/scripts.pory"
	lock
# 31 "data/maps/JubilifeCompanyF1/scripts.pory"
	msgbox PoketchCo1F_Text_WithTV_Text_0, MSGBOX_NPC
# 33 "data/maps/JubilifeCompanyF1/scripts.pory"
	release
	return


PoketchCo1F_Text_President::
# 37 "data/maps/JubilifeCompanyF1/scripts.pory"
	lock
# 38 "data/maps/JubilifeCompanyF1/scripts.pory"
	msgbox PoketchCo1F_Text_President_Text_0, MSGBOX_NPC
# 43 "data/maps/JubilifeCompanyF1/scripts.pory"
	release
	return


PoketchCo1F_Text_WelcomeToThePoketchCompany_Text_0:
# 5 "data/maps/JubilifeCompanyF1/scripts.pory"
	.string "Welcome to the Pokétch Company.\p"
	.string "We’re actually a family-run business,\n"
	.string "so we’re not very impressive.$"

PoketchCo1F_Text_OhYouCanBeSureIWillKeepDevelopingPoketchApps_Text_0:
# 13 "data/maps/JubilifeCompanyF1/scripts.pory"
	.string "Oh, you can be sure I will keep\n"
	.string "developing Pokétch apps.\p"
	.string "Just like Pokémon, my Pokétch is\n"
	.string "something that evolves!$"

PoketchCo1F_Text_HeyDoYouWatchTV_Text_0:
# 22 "data/maps/JubilifeCompanyF1/scripts.pory"
	.string "Hey, do you watch TV?\n"
	.string "“Pokétch Detective” is a great show.\p"
	.string "Seeing that program compels me to use\n"
	.string "my Pokétch more!$"

PoketchCo1F_Text_WithTV_Text_0:
# 31 "data/maps/JubilifeCompanyF1/scripts.pory"
	.string "Hello!\n"
	.string "I'm with Jubilife TV!$"

PoketchCo1F_Text_President_Text_0:
# 38 "data/maps/JubilifeCompanyF1/scripts.pory"
	.string "Hi, hi!\p"
	.string "I'm the president of the Pokétch\n"
	.string "Company!\p"
	.string "I'm developing a new Pokétch app.\n"
	.string "but it's not quite done.$"
